stages:
  - build
  - deploy

variables:
  TF_VAR_project_id: "your-project-id"
  TF_VAR_credentials_file: "path/to/your/service-account.json"

before_script:
  - apt-get update -y
  - apt-get install -y wget unzip
  - wget https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
  - unzip terraform_1.0.9_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform --version
  - terraform init

build_docker_image:
  stage: build
  script:
    # docker login will authenticate the job with the container registry
    # $CI_REGISTRY_USERNAME, $CI_REGISTRY_PASSWORD, $CI_REGISTRY are GitLab built-in variables
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - "echo I am building the docker image!"
    - docker build -t registry.gitlab.com/ompatel4799/my_project:$CI_COMMIT_SHORT_SHA .
    - docker push registry.gitlab.com/ompatel4799/my_project:$CI_COMMIT_SHORT_SHA

deploy_kubernetes:
  stage: deploy
  script:
    - terraform apply -auto-approve
  only:
    changes:
      - main.tf
